version: '3.1'

networks:
 dev:
  driver: bridge

services:
  my-app:
    image: my-app:latest
    depends_on:
      - "app_db"
    container_name: app_api
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Username=etmdb;Password=123;Host=app_db;Port=5432;Database=etmdb;
      - ASPNETCORE_URLS=http://+:80
    networks:
     - dev

  app_db:
    image: postgres
    container_name: app_db
    restart: always
    environment:
      - POSTGRES_USER=etmdb
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=etmdb
    ports:
      - '5432:5432'
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
     - dev
volumes:
  app_data: